name: mathforkids
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Madimi
      fonts:
        - asset: assets/fonts/MadimiOne-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: IriGrov
      fonts:
        - asset: assets/fonts/IrishGrover-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
